import React from 'react';
import Head from 'next/head';

import { About, Footer, Header, Skills, Work } from '@/container';
import { Navbar } from '@/components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Alexander`s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='app'>
        <Navbar/>
        <Header/>
        <About/>
        <Work/>
        <Skills/>
        <Footer/>
      </main>
    </>
  )
}
